package/gluon-core: gluon-reload print error message into stderr
Signed-off-by: Jan-Tarek Butt <tarek@ring0.de>

diff --git a/package/gluon-core/files/usr/bin/gluon-reload b/package/gluon-core/files/usr/bin/gluon-reload
--- a/package/gluon-core/files/usr/bin/gluon-reload
+++ b/package/gluon-core/files/usr/bin/gluon-reload
@@ -10,7 +10,7 @@ for script in *; do
 done
 
 if [ $err -eq 1 ]; then
-	echo 'One or more daemons failed to reload.'
+	echo 'One or more daemons failed to reload.' >&2
 	exit 1
 fi
 
